export const projects = [
  {
    title: "Portfolloid",
    description:
      "Сайт-визитка, сайт-портфолио, сайт-песочница, в которой я строю свои замки и леплю свои куличики. Его репозиторий на GitHub публичный, как и у других проектов здесь, а размещён он на Vercel.",
    src: "portfolloid.png",
    link: "https://ocelloid.com/",
    icon: "/images/favicon.png",
    repo: "https://github.com/ocelloid/portfolloid",
    color: "#475569bf",
    stack: [
      "next.js",
      "tailwind",
      "TypeScript",
      "react",
      "vercel",
      "drizzle",
      "clerk",
      "shadcn/ui",
      "gsap",
      "zod",
    ],
  },
  {
    title: "Libra",
    description:
      "Сайт-органайзер для совместной работы и обсуждения проектов. Нацелен на то, чтобы сотрудники могли быстро и эффективно создавать подзадачи, определять их приоритеты и обсуждать их.",
    src: "libra.png",
    link: "https://libra.ocelloid.com/",
    icon: "/images/favicon_libra.png",
    repo: "https://github.com/ocelloid/libra",
    color: "#3b5995",
    stack: [
      "next.js",
      "tailwind",
      "TypeScript",
      "react",
      "vercel",
      "prisma",
      "trpc",
      "nextauth",
      "next/ui",
      "websocket",
    ],
  },
  {
    title: "Маскарад Вампиров",
    description:
      "Сайт для городской ролевой игры Маскарад Вампиров, на котором можно играть, создавать истории и персонажей, получать информацию о происходящих событиях, закупаться симпатичным мерчем.",
    src: "vtmsu.png",
    link: "https://vtm.su/",
    icon: "/images/favicon_vtmsu.png",
    repo: "https://github.com/ocelloid/vtmsu",
    color: "#dc2626",
    stack: [
      "next.js",
      "tailwind",
      "TypeScript",
      "react",
      "vercel",
      "prisma",
      "trpc",
      "nextauth",
      "next/ui",
      "zod",
    ],
  },
];
